stages:
  - test
  - build

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

test:
  extends: .go-cache
  image: ${CI_REGISTRY_IMAGE}/library/golang:1.19.3-bullseye
  script:
    - go test -v -race $(go list ./... | grep -v /vendor/)
  cache:

docker:
  stage: build
  image:
    name: ${CI_REGISTRY_IMAGE}/library/kaniko-project-executor:v1.9.1-debug
    entrypoint: [""]
  script:
    - DOCKER_IMAGE_TAG="latest"
    - if [ -n "$CI_COMMIT_TAG" ]; then DOCKER_IMAGE_TAG="$CI_COMMIT_TAG"; fi
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${DOCKER_IMAGE_TAG}"
      --build-arg "API_VERSION=${DOCKER_IMAGE_TAG}"
      --build-arg "BASE_IMAGE_PREFIX=${CI_REGISTRY_IMAGE}/"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
