apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: lcm-engine
spec:
  basicAuth:
    secret: auth-secret
    headerField: X-Forwarded-User
    removeHeader: true
