apiVersion: apps/v1
kind: Deployment
metadata:
  name: lcm-engine-db
  namespace: lcm-engine
spec:
  selector:
    matchLabels:
      app: lcm-engine-db
  template:
    metadata:
      labels:
        app: lcm-engine-db
    spec:
      securityContext:
        fsGroup: 0
      containers:
      - name: lcm-engine-db
        image: public.ecr.aws/bitnami/postgresql:15.2.0-debian-11-r5
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRESQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: lcm-engine-db
                key: username
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lcm-engine-db
                key: password
          - name: POSTGRESQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: lcm-engine-db
                key: database
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /bitnami/postgresql
            name: db-persistance
            readOnly: false
      volumes:
        - name: db-persistance
          persistentVolumeClaim:
            claimName: lcm-engine-db


