apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lcm-engine-db
  namespace: lcm-engine
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: default
