# coding: utf-8

from __future__ import absolute_import


from lcm_engine.models.base_model_ import Model
from lcm_engine import util


class ContainerHealth(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NONEXISTENT = "nonexistent"
    STOPPED = "stopped"
    RUNNING = "running"
    UNKNOWN = "unknown"

    def __init__(self):  # noqa: E501
        """ContainerHealth - a model defined in OpenAPI"""
        self.openapi_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "ContainerHealth":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ContainerHealth of this ContainerHealth.  # noqa: E501
        :rtype: ContainerHealth
        """
        return util.deserialize_model(dikt, cls)
