# coding: utf-8

from __future__ import absolute_import


from lcm_engine.models.base_model_ import Model
from lcm_engine import util


class Error(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, msg=None):  # noqa: E501
        """Error - a model defined in OpenAPI

        :param msg: The msg of this Error.  # noqa: E501
        :type msg: str
        """
        self.openapi_types = {"msg": str}

        self.attribute_map = {"msg": "msg"}

        self.msg = msg

    @classmethod
    def from_dict(cls, dikt) -> "Error":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.  # noqa: E501
        :rtype: Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def msg(self):
        """Gets the msg of this Error.


        :return: The msg of this Error.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg):
        """Sets the msg of this Error.


        :param msg: The msg of this Error.
        :type msg: str
        """
        if msg is None:
            raise ValueError(
                "Invalid value for `msg`, must not be `None`"
            )  # noqa: E501

        self._msg = msg
