name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main  # oder dein Haupt-Branch

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r documentation/requirements.txt

      - name: Build Sphinx docs
        run: |
          sphinx-build -b html documentation/docs build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
          publish_branch: gh-pages
